# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/m7wlj/setup-makefiles.sh

PRODUCT_COPY_FILES += \
        vendor/htc/m7wlj/proprietary/bin/efsks:/system/bin/efsks \
        vendor/htc/m7wlj/proprietary/bin/qcks:/system/bin/qcks \
        vendor/htc/m7wlj/proprietary/vendor/firmware/mfg.bin:/system/vendor/firmware/mfg.bin \
        vendor/htc/m7wlj/proprietary/lib/libril-qc-qmi-1.so:/system/lib/libril-qc-qmi-1.so \
        vendor/htc/m7wlj/proprietary/lib/libril-qcril-hook-oem.so:/system/lib/libril-qcril-hook-oem.so \
	vendor/htc/m7wlj/proprietary/lib/hw/sensors.m7wlj.so:/system/lib/hw/sensors.m7wlj.so \
	vendor/htc/m7wlj/proprietary/lib/libBMLSupports.so:/system/lib/libBMLSupperts.so \
	vendor/htc/m7wlj/proprietary/lib/libCdAbLayer.so:/system/lib/libCdAbLayer.so \
	vendor/htc/m7wlj/proprietary/lib/libJellyPG.so:/system/lib/libJellyPG.so \
	vendor/htc/m7wlj/proprietary/lib/libMTVMFCls.so:/system/lib/libMTVMFCls.so \
	vendor/htc/m7wlj/proprietary/lib/libnm325.so:/system/lib/libnm325.so \
	vendor/htc/m7wlj/proprietary/bin/jellyservice:/system/bin/jellyservice \
	vendor/htc/m7wlj/proprietary/bin/mtvmfservice:/system/bin/mtvmfservice \
	vendor/htc/m7wlj/proprietary/bin/mtvmfrecservice:/system/bin/mtvmfrecservice \
	vendor/htc/m7wlj/proprietary/bin/felica_agent:/system/bin/felica_agent \
	vendor/htc/m7wlj/proprietary/bin/felica_daemon:/system/bin/felica_daemon \
	vendor/htc/m7wlj/proprietary/bin/felica_startup:/system/bin/felica_startup \
	vendor/htc/m7wlj/proprietary/etc/felica/common.cfg:/system/etc/felica/common.cfg \
	vendor/htc/m7wlj/proprietary/etc/felica/mfm.cfg:/system/etc/felica/mfm.cfg \
	vendor/htc/m7wlj/proprietary/etc/felica/mfs.cfg:/system/etc/felica/mfs.cfg \
        vendor/htc/m7wlj/proprietary/app/KDDI_Felicalock.apk:/system/app/KDDI_Felicalock.apk \
        vendor/htc/m7wlj/proprietary/app/MobileFeliCaClient.apk:/system/app/MobileFeliCaClient.apk \
        vendor/htc/m7wlj/proprietary/app/MobileFeliCaMenuApp.apk:/system/app/MobileFeliCaMenuApp.apk \
        vendor/htc/m7wlj/proprietary/app/MobileFeliCaSettingApp.apk:/system/app/MobileFeliCaSettingApp.apk \
        vendor/htc/m7wlj/proprietary/app/MobileFeliCaWebPluginBoot.apk:/system/app/MobileFeliCaWebPluginBoot.apk \
	vendor/htc/m7wlj/proprietary/app/GMobileTV.apk:/system/app/GMobileTV.apk
